# Site settings
title: Emily J. Fan
email: emilyjustinefan@gmail.com
url: https://emilyjfan.github.io
description: "Emily Fan's site on the world wide web!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 545454
  secondary: 70E8CB
  secondary-dark: 333333

# Footer settings
footer:
  copyright: Emily J. Fan
  social: Let's Connect!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/emilyjustinefan
  - title: linkedin
    url: https://ca.linkedin.com/in/emilyjustinefan
  - title: github
    url: http://github.com/emilyjfan

# Build settings
markdown: kramdown
permalink: pretty
