# Site settings
title: Emily J. Fan
email: emilyjustinefan@gmail.com
url: https://example.github.io
description: "Emily's site on the world wide web!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F06060 #80B3FF
  secondary: 8CBEB2 #FD6E8A
  secondary-dark: 5C4B51 #A2122F

# Footer settings
footer:
  copyright: Emily J. Fan
  # location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/emilyjustinefan
  - title: linkedin
    url: https://ca.linkedin.com/in/emilyjustinefan
  - title: github
    url: http://github.com/emilyjfan

# Build settings
markdown: kramdown
permalink: pretty
